
--  V1.0__Create_Schema_game.sql

--Schema: game

DROP SCHEMA IF EXISTS game CASCADE;
COMMIT;

CREATE SCHEMA game AUTHORIZATION postgres;

--Table: game


CREATE TABLE game (
  gameid     integer NOT NULL,
  starttime  timestamp without time zone,
  );

--Table: player

CREATE TABLE player (
  playerid  integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  gameid    integer NOT NULL,
  playernm  varchar(30),
  score     integer,
  );

COMMIT;
