--Schema: question

DROP SCHEMA question

CREATE SCHEMA question AUTHORIZATION postgres;

--Table: question.question

DROP TABLE question.question;

CREATE TABLE question.question (
  questionid    integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  questiontext  varchar(1000) NOT NULL
) WITH (
    OIDS = FALSE
  );

--Table: question.answer

DROP TABLE question.answer;

CREATE TABLE question.answer (
  answerid     integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  questionid   integer NOT NULL,
  answertext   varchar(250) NOT NULL,
  correctflag  boolean,
  /* Foreign keys */
  CONSTRAINT questionid
    FOREIGN KEY (questionid)
    REFERENCES question.question(questionid)
) WITH (
    OIDS = FALSE
  );