
--  V1.1__Create_Schema_question.sql

--Schema: question

DROP SCHEMA IF EXISTS question CASCADE ;
COMMIT;

CREATE SCHEMA question AUTHORIZATION postgres;

CREATE TABLE question (
  questionid    integer NOT NULL,
  questiontext  varchar(300) NOT NULL,
  );

CREATE TABLE answer (
  answerid     integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  questionid   integer NOT NULL,
  answertext   varchar(300) NOT NULL,
  correctflag  boolean,
  );

COMMIT;