
--  V1.5__Load_Table_answer.sql

DELETE FROM question.answer;
COMMIT;

INSERT INTO question.answer (questionid, answertext, correctflag) VALUES
  (1, '8', false),
  (1, '12', true),
  (1, '15', false),
  (1, '10', false),
  (2, '3', false),
  (2, '0', false),
  (2, '1', false),
  (2, '2', true),
  (3, '8', true),
  (3, '12', false),
  (3, '5', false),
  (3, '10', false),
  (4, '4', true),
  (4, '3', false),
  (4, '2', false),
  (4, '1', false),
  (5, 'Monthly', false),
  (5, 'Eight times a year', true),
  (5, 'Semi-Annually', false),
  (5, 'Quarterly', false),
  (6, 'Christopher J. Waller', false),
  (6, 'Janet Yellen', false),
  (6, 'Jerome H. Powell', false),
  (6, 'James Bullard', true),
  (7, 'Asset', true),
  (7, 'Productivity', false),
  (7, 'Liability', false),
  (7, 'Unit of account', false),
  (8, 'Currency', false),
  (8, 'Money Supply', false),
  (8, 'Checking deposits', false),
  (8, 'Money', true),
  (9, 'Federal Reserve System', false),
  (9, 'Quantity Equation of Money', false),
  (9, 'Target Inflation Rate', true),
  (9, 'Marginal Propensity to Consume', false),
 (10, 'Federal Open Market Committee', false),
 (10, 'Federal Reserve System', false),
 (10, 'Federal Funds Rate', false),
 (10, 'Open Market Operation', true),
 (11, 'Store of Value', false),
 (11, 'Required Reserve Ratio', true),
 (11, 'Checking Deposits', false),
 (11, 'Inflation', false),
 (12, 'Federal Funds Rate', true),
 (12, 'Required Reserve Ratio', false),
 (12, 'Reserves', false),
 (12, 'Consumption Function', false),
 (13, 'Asset', false),
 (13, 'Liability', true),
 (13, 'Reserves', false),
 (13, 'Store of Value', false),
 (14, 'Velocity', true),
 (14, 'Reserves', false),
 (14, 'Money Supply', false),
 (14, 'Frequency', false),
 (15, 'Assets', false),
 (15, 'Liabilities', false),
 (15, 'Reserves', true),
 (15, 'Deposits', false)
;

COMMIT;
